# Complete task definition
- name: Install Docker SDK for Python
  # Add necessary lines here
  package:
    name: python3-docker

- name: Build Docker images from Dockerfiles
  docker_image:
    name: "{{ item.name }}"
    source: build
    build:
      path: "/vagrant/provisioning/dockerfiles/{{ item.directory }}"
      pull: true
    state: present
    force_source: yes
  loop:
    - { name: "{{ webapp_img }}", directory: webapp }
    - { name: "{{ db_img }}", directory: db }

- name: Create network
  docker_network:
  # Add necessary lines here
    name: "{{ network }}"
    driver: "bridge"

- name: Run MySQL container
  docker_container:
  # Add necessary lines here
    name: "{{ db_container }}"
    image: "{{ db_img }}"
    purge_networks: true
    networks:
      - name: "{{ network }}"

- name: Run Flask container
  docker_container:
  # Add necessary lines here
    name: "{{ webapp_container }}"
    image: "{{ webapp_img }}"
    purge_networks: true
    networks:
      - name: "{{ network }}"
    ports: 80:5000