# Add roles definition
- src: geerlingguy.firewall
  version: 3.3.0

- src: geerlingguy.mysql
  version: 4.3.2

- src: geerlingguy.apache
  version: 4.8.0

- src: geerlingguy.php-mysql
  version: 2.1.0

- src: geerlingguy.php
  version: 2.5.1
