# Add roles definition
- name: geerlingguy.firewall
  version: 3.2.0

- name: geerlingguy.mysql
  version: 3.10.0

- name: geerlingguy.apache
  version: 5.2.1

- name: geerlingguy.php-mysql
  version: 2.8.0

- name: geerlingguy.php
  version: 4.7.0
